services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /data/home-theater:/data
      - ${PWD}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
